### ISSUE TITLE
get_doc_id_list.py

### ISSUE THREAD

**Issue by August-fire** [tigeriaf/wenshu_spider#1]
get_doc_id_list.py 里面的参数v，月初（1-9号）的时候应该要在日期前面加个0吧。

**Comment by tigeriaf** [comment]
v = str(d_time.tm_year) + str(d_time.tm_mon).zfill(2) + str(d_time.tm_mday)  其中的str(d_time.tm_mon).zfill(2)是会在1-9前面补0的
